[tool.pytest.ini_options]
testpaths = [
    "./Scripts/UnitTest",
]
pythonpath = [
    "."
]
markers = [
    "local: marks tests that should only run locally (deselect with '-m \"not local\"')"
]

[tool.pyright]
include = [
    "DataLoader", "Evaluation", "Module", "Odometry",
    "Scripts", "Train", "Utility", "*.py"
]
exclude = [
    "./Module/Network/PWCNet",              # Third-party lib
    "./Module/Network/FlowFormer",          # Third-party lib
    "./Odometry/BaselineDPVO.py",           # Need install DPVO and compile cuda kernel
    "./Scripts/AdHoc/FLOPS_analyzer.py",    # Need additional package fvcore
]
typeCheckingMode = "standard"
reportImportCycles = "error"
reportDuplicateImport = "error"
reportAbstractUsage = "warning"
reportPrivateImportUsage = "information"
stubPath = "./stubs"
