#*IS_DATASET_TYPE*#
# This file contains the two test environments used by TartanVO Stereo Module
type: TartanAir
ips: 100
compressed: true

# Controls optional data sources
gtDepth: false
gtFlow: true
gtPose: true
useIMU: false

begin_idx: 0
end_idx: -1

dataroot: PATH_FOR_TARTANAIR

# Paths
roots:
  # Seaside Town
  - root: /house/Data/P001
    name: house001
  - root: /house/Data/P006
    name: house006
  - root: /house/Data/P008
    name: house008
  - root: /house/Data/P002
    name: house002
  - root: /house/Data/P005
    name: house005
  - root: /house/Data/P007
    name: house007
  - root: /house/Data/P000
    name: house000
  - root: /house/Data/P004
    name: house004
  - root: /house/Data/P003
    name: house003
  - root: /house_dist0/Data/P006
    name: house_dist0006
  - root: /house_dist0/Data/P001
    name: house_dist0001
  - root: /house_dist0/Data/P005
    name: house_dist0005
  - root: /house_dist0/Data/P002
    name: house_dist0002
  - root: /house_dist0/Data/P000
    name: house_dist0000
  - root: /house_dist0/Data/P003
    name: house_dist0003
  - root: /house_dist0/Data/P004
    name: house_dist0004
  - root: /slaughter/Data/P000
    name: slaughter000
  - root: /slaughter/Data/P007
    name: slaughter007
  - root: /slaughter/Data/P003
    name: slaughter003
  - root: /slaughter/Data/P004
    name: slaughter004
  - root: /slaughter/Data/P006
    name: slaughter006
  - root: /slaughter/Data/P001
    name: slaughter001
  - root: /slaughter/Data/P005
    name: slaughter005
  - root: /slaughter/Data/P008
    name: slaughter008
  - root: /slaughter/Data/P002
    name: slaughter002
  - root: /abandonedfactory/Data/P004
    name: abandonedfactory004
  - root: /abandonedfactory/Data/P003
    name: abandonedfactory003
  - root: /abandonedfactory/Data/P007
    name: abandonedfactory007
  - root: /abandonedfactory/Data/P000
    name: abandonedfactory000
  # - root: /abandonedfactory/Data/P002 # Testing set
  #   name: abandonedfactory002
  - root: /abandonedfactory/Data/P008
    name: abandonedfactory008
  - root: /abandonedfactory/Data/P005
    name: abandonedfactory005
  - root: /abandonedfactory/Data/P001
    name: abandonedfactory001
  - root: /abandonedfactory/Data/P006
    name: abandonedfactory006
  - root: /abandonedfactory_night/Data/P002
    name: abandonedfactory_night002
  - root: /abandonedfactory_night/Data/P008
    name: abandonedfactory_night008
  - root: /abandonedfactory_night/Data/P005
    name: abandonedfactory_night005
  - root: /abandonedfactory_night/Data/P001
    name: abandonedfactory_night001
  - root: /abandonedfactory_night/Data/P006
    name: abandonedfactory_night006
  - root: /abandonedfactory_night/Data/P004
    name: abandonedfactory_night004
  - root: /abandonedfactory_night/Data/P003
    name: abandonedfactory_night003
  - root: /abandonedfactory_night/Data/P007
    name: abandonedfactory_night007
  - root: /abandonedfactory_night/Data/P000
    name: abandonedfactory_night000
  - root: /westerndesert/Data/P005
    name: westerndesert005
  - root: /westerndesert/Data/P002
    name: westerndesert002
  - root: /westerndesert/Data/P006
    name: westerndesert006
  - root: /westerndesert/Data/P001
    name: westerndesert001
  - root: /westerndesert/Data/P003
    name: westerndesert003
  - root: /westerndesert/Data/P004
    name: westerndesert004
  # - root: /westerndesert/Data/P000
  #   name: westerndesert000
  - root: /westerndesert/Data/P007
    name: westerndesert007
  - root: /ocean/Data/P005
    name: ocean005
  - root: /ocean/Data/P008
    name: ocean008
  # - root: /ocean/Data/P002
  #   name: ocean002
  - root: /ocean/Data/P006
    name: ocean006
  - root: /ocean/Data/P001
    name: ocean001
  - root: /ocean/Data/P003
    name: ocean003
  - root: /ocean/Data/P004
    name: ocean004
  - root: /ocean/Data/P000
    name: ocean000
  - root: /ocean/Data/P007
    name: ocean007
  - root: /soulcity/Data/P004
    name: soulcity004
  - root: /soulcity/Data/P009
    name: soulcity009
  - root: /soulcity/Data/P003
    name: soulcity003
  - root: /soulcity/Data/P010
    name: soulcity010
  - root: /soulcity/Data/P007
    name: soulcity007
  - root: /soulcity/Data/P000
    name: soulcity000
  - root: /soulcity/Data/P002
    name: soulcity002
  - root: /soulcity/Data/P008
    name: soulcity008
  - root: /soulcity/Data/P005
    name: soulcity005
  - root: /soulcity/Data/P001
    name: soulcity001
  - root: /soulcity/Data/P006
    name: soulcity006
  # - root: /oldtown/Data/P003
  #   name: oldtown003
  - root: /oldtown/Data/P004
    name: oldtown004
  - root: /oldtown/Data/P000
    name: oldtown000
  - root: /oldtown/Data/P007
    name: oldtown007
  - root: /oldtown/Data/P005
    name: oldtown005
  - root: /oldtown/Data/P002
    name: oldtown002
  - root: /oldtown/Data/P006
    name: oldtown006
  - root: /oldtown/Data/P001
    name: oldtown001
  - root: /office2/Data/P001
    name: office2001
  - root: /office2/Data/P006
    name: office2006
  - root: /office2/Data/P002
    name: office2002
  - root: /office2/Data/P005
    name: office2005
  - root: /office2/Data/P000
    name: office2000
  - root: /office2/Data/P004
    name: office2004
  - root: /office2/Data/P003
    name: office2003
  - root: /office/Data/P001
    name: office001
  - root: /office/Data/P005
    name: office005
  - root: /office/Data/P002
    name: office002
  - root: /office/Data/P000
    name: office000
  - root: /office/Data/P003
    name: office003
  - root: /office/Data/P004
    name: office004
  - root: /amusement/Data/P007
    name: amusement007
  # - root: /amusement/Data/P000
  #   name: amusement000
  - root: /amusement/Data/P004
    name: amusement004
  - root: /amusement/Data/P003
    name: amusement003
  - root: /amusement/Data/P001
    name: amusement001
  - root: /amusement/Data/P006
    name: amusement006
  - root: /amusement/Data/P002
    name: amusement002
  - root: /amusement/Data/P005
    name: amusement005
  # - root: /japanesealley/Data/P000
  #   name: japanesealley000
  - root: /japanesealley/Data/P007
    name: japanesealley007
  - root: /japanesealley/Data/P003
    name: japanesealley003
  - root: /japanesealley/Data/P004
    name: japanesealley004
  - root: /japanesealley/Data/P006
    name: japanesealley006
  - root: /japanesealley/Data/P001
    name: japanesealley001
  - root: /japanesealley/Data/P005
    name: japanesealley005
  - root: /japanesealley/Data/P002
    name: japanesealley002
  - root: /seasonsforest/Data/P003
    name: seasonsforest003
  - root: /seasonsforest/Data/P004
    name: seasonsforest004
  # - root: /seasonsforest/Data/P000
  #   name: seasonsforest000
  - root: /seasonsforest/Data/P007
    name: seasonsforest007
  - root: /seasonsforest/Data/P005
    name: seasonsforest005
  - root: /seasonsforest/Data/P002
    name: seasonsforest002
  - root: /seasonsforest/Data/P006
    name: seasonsforest006
  - root: /seasonsforest/Data/P001
    name: seasonsforest001
  - root: /endofworld/Data/P006
    name: endofworld006
  - root: /endofworld/Data/P001
    name: endofworld001
  - root: /endofworld/Data/P005
    name: endofworld005
  - root: /endofworld/Data/P002
    name: endofworld002
  - root: /endofworld/Data/P000
    name: endofworld000
  - root: /endofworld/Data/P007
    name: endofworld007
  - root: /endofworld/Data/P003
    name: endofworld003
  - root: /endofworld/Data/P004
    name: endofworld004
  - root: /seasonsforest_winter/Data/P002
    name: seasonsforest_winter002
  - root: /seasonsforest_winter/Data/P005
    name: seasonsforest_winter005
  - root: /seasonsforest_winter/Data/P001
    name: seasonsforest_winter001
  - root: /seasonsforest_winter/Data/P006
    name: seasonsforest_winter006
  - root: /seasonsforest_winter/Data/P004
    name: seasonsforest_winter004
  - root: /seasonsforest_winter/Data/P003
    name: seasonsforest_winter003
  - root: /hospital/Data/P002
    name: hospital002
  - root: /hospital/Data/P008
    name: hospital008
  - root: /hospital/Data/P011
    name: hospital011
  - root: /hospital/Data/P016
    name: hospital016
  - root: /hospital/Data/P005
    name: hospital005
  - root: /hospital/Data/P001
    name: hospital001
  - root: /hospital/Data/P012
    name: hospital012
  - root: /hospital/Data/P015
    name: hospital015
  - root: /hospital/Data/P006
    name: hospital006
  - root: /hospital/Data/P004
    name: hospital004
  - root: /hospital/Data/P017
    name: hospital017
  - root: /hospital/Data/P010
    name: hospital010
  - root: /hospital/Data/P009
    name: hospital009
  - root: /hospital/Data/P003
    name: hospital003
  - root: /hospital/Data/P007
    name: hospital007
  - root: /hospital/Data/P014
    name: hospital014
  - root: /hospital/Data/P013
    name: hospital013
  - root: /hospital/Data/P000
    name: hospital000
  - root: /carwelding/Data/P003
    name: carwelding003
  - root: /carwelding/Data/P004
    name: carwelding004
  - root: /carwelding/Data/P000
    name: carwelding000
  - root: /carwelding/Data/P007
    name: carwelding007
  - root: /carwelding/Data/P005
    name: carwelding005
  - root: /carwelding/Data/P002
    name: carwelding002
  - root: /carwelding/Data/P006
    name: carwelding006
  - root: /carwelding/Data/P001
    name: carwelding001
  - root: /gascola/Data/P006
    name: gascola006
  - root: /gascola/Data/P001
    name: gascola001
  - root: /gascola/Data/P005
    name: gascola005
  - root: /gascola/Data/P002
    name: gascola002
  # - root: /gascola/Data/P000
  #   name: gascola000
  - root: /gascola/Data/P003
    name: gascola003
  - root: /gascola/Data/P004
    name: gascola004
  - root: /neighborhood/Data/P007
    name: neighborhood007
  - root: /neighborhood/Data/P000
    name: neighborhood000
  - root: /neighborhood/Data/P013
    name: neighborhood013
  - root: /neighborhood/Data/P004
    name: neighborhood004
  - root: /neighborhood/Data/P009
    name: neighborhood009
  - root: /neighborhood/Data/P003
    name: neighborhood003
  - root: /neighborhood/Data/P010
    name: neighborhood010
  - root: /neighborhood/Data/P012
    name: neighborhood012
  - root: /neighborhood/Data/P001
    name: neighborhood001
  - root: /neighborhood/Data/P006
    name: neighborhood006
  - root: /neighborhood/Data/P011
    name: neighborhood011
  - root: /neighborhood/Data/P002
    name: neighborhood002
  - root: /neighborhood/Data/P008
    name: neighborhood008
  - root: /neighborhood/Data/P005
    name: neighborhood005

