#*IS_DATASET_TYPE*#
# This file contains the KITTI Odometry sequence 00 to 02 (inclusive)

type: KITTISequence

# Camera calibration and distortion parameters (OpenCV) 
fx: 718.856
fy: 718.856
cx: 607.1928
cy: 185.2157
bl: 0.53716

target_size: [376, 680]

# Controls optional data sources
gtDepth: false
gtFlow: false
gtPose: true

begin_idx: 0
end_idx: -1

dataroot: PATH_FOR_KITTI

# Paths
roots:
  - root: sequences/00
    name: K00
  - root: sequences/01
    name: K01
  - root: sequences/02
    name: K02
