#*IS_DATASET_TYPE*#
# This file contains the KITTI Odometry sequence 00 to 02 (inclusive)

type: KITTISequence

# Camera calibration and distortion parameters (OpenCV) 
fx: 707.0912
fy: 707.0912
cx: 601.8873
cy: 183.1104
bl: 0.53715

target_size: [376, 680]

# Controls optional data sources
gtDepth: false
gtFlow: false
gtPose: true

begin_idx: 0
end_idx: -1

dataroot: PATH_FOR_KITTI

# Paths
roots:
  - root: sequences/04
    name: K04
  - root: sequences/05
    name: K05
  - root: sequences/06
    name: K06
  - root: sequences/07
    name: K07
  - root: sequences/08
    name: K08
  - root: sequences/09
    name: K09
  - root: sequences/10
    name: K10
