type: Zed
name: kit2kit_manual_dyna
root: "PATH_FOR_ZED/traverses/kit2kit_manual_dyna"

# Additional argument for Zed.
scaleu: 3
scalev: 2.5

# Camera Calibration
fx: 735.9240
fy: 735.7140
cx: 964.8520
cy: 622.2050
bl: 0.119981

width: 1920
height: 1200

# Controls optional data sources
gtDepth: false
gtFlow: false
gtPose: false
