type: Zed
name: straight_line_cam_side
root: "PATH_FOR_ZED/traverses/straight_line_cam_side"

# Additional argument for Zed.
scaleu: 3
scalev: 2.5
skip: 10

# Camera Intrinsics
fx: 735.9240
fy: 735.7140
cx: 964.8520
cy: 622.2050
bl: 0.119981

width: 1920
height: 1200

# Controls optional data sources
gtDepth: false
gtFlow: false
gtPose: false
